Update build-kernel-dts-env.yml

diff --git a/.github/workflows/build-kernel-dts-env.yml b/.github/workflows/build-kernel-dts-env.yml
--- a/.github/workflows/build-kernel-dts-env.yml
+++ b/.github/workflows/build-kernel-dts-env.yml
@@ -29,7 +29,14 @@ jobs:
         run: |
           CUSTOM_DTS="temp_dts_repo/dts/rk3399-nanopi4-rev00.dts"
           TARGET_DTS="arch/arm64/boot/dts/rockchip/rk3399-nanopi4-rev00.dts"
-
+          
+          echo "Cloning nanopct4_i2s repository for DTS"
+          git clone --depth=1 https://github.com/3684993/nanopct4_i2s.git temp_dts_repo
+          if [ ! -d "temp_dts_repo/dts" ]; then
+             echo "DTS folder not found in nanopct4_i2s repository!"
+             exit 1
+          fi
+          
           if [ -f "$CUSTOM_DTS" ]; then
              echo "Replacing DTS: $CUSTOM_DTS → $TARGET_DTS"
              cp "$CUSTOM_DTS" "$TARGET_DTS"
