Update build-kernel-dts-env.yml

diff --git a/.github/workflows/build-kernel-dts-env.yml b/.github/workflows/build-kernel-dts-env.yml
--- a/.github/workflows/build-kernel-dts-env.yml
+++ b/.github/workflows/build-kernel-dts-env.yml
@@ -18,15 +18,22 @@ jobs:
         with:
           repository: friendlyarm/kernel-rockchip
           ref: nanopi4-v4.19.y
+      - name: Debug repo root
+        run: |
+          echo "Current working directory: $(pwd)"
+          echo "Files in current directory:"
+          ls -alh
+          echo "Recursive list:"
+          ls -R .
           
       - name: Install cross-compiler
         run: |
           sudo apt update
           sudo apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
 
-      - name: Enable I2S1 in Device Tree
+      - name: Replace DTS with custom file
         run: |
-          CUSTOM_DTS="dts/rk3399-nanopi4-rev00.dts"
+          CUSTOM_DTS="./dts/rk3399-nanopi4-rev00.dts"
           DTS_FILE="arch/arm64/boot/dts/rockchip/rk3399-nanopi4-rev00.dts"
           
           if [ -f "$CUSTOM_DTS" ]; then
@@ -37,8 +44,8 @@ jobs:
              exit 1
           fi
 
-          echo "✅ DTS replaced, validating..."
-          dtc -I dts -O dtb -o /dev/null "$TARGET_DTS" || (echo "❌ DTS syntax error!" && exit 1) 
+          echo "DTS replaced, validating..."
+          dtc -I dts -O dtb -o /dev/null "$TARGET_DTS" || (echo "DTS syntax error!" && exit 1) 
 
       - name: Compile kernel and device tree
         run: |
