Update build-kernel-dts-env.yml

diff --git a/.github/workflows/build-kernel-dts-env.yml b/.github/workflows/build-kernel-dts-env.yml
--- a/.github/workflows/build-kernel-dts-env.yml
+++ b/.github/workflows/build-kernel-dts-env.yml
@@ -31,14 +31,22 @@ jobs:
           TARGET_DTS="arch/arm64/boot/dts/rockchip/rk3399-nanopi4-rev00.dts"
           
           echo "PWD: $(pwd)"
+          
           echo "Cloning nanopct4_i2s repository for DTS"
           git clone --depth=1 https://github.com/3684993/nanopct4_i2s.git temp_dts_repo
           if [ ! -d "temp_dts_repo/dts" ]; then
              echo "DTS folder not found in nanopct4_i2s repository!"
              exit 1
           fi  
-          ls -alf temp_dts_repo/dts/
+
           if [ -f "$CUSTOM_DTS" ]; then
+             echo "DTS CUSTOM_DTS"
+             dtc -I dts -O dtb -o /dev/null "$CUSTOM_DTS" || (echo "DTS syntax error!" && exit 1)
+             ls -alf 
+             echo "DTS TARGET_DTS"
+             dtc -I dts -O dtb -o /dev/null "$TARGET_DTS" || (echo "DTS syntax error!" && exit 1)
+             ls -alf 
+             
              echo "Replacing DTS: $CUSTOM_DTS → $TARGET_DTS"
              cp "$CUSTOM_DTS" "$TARGET_DTS"
           else
